name: "Test Token Logos"
on:
  push:
    branches:
      - master
    paths:
      - "logos/token-logos/network/**/**"
  pull_request:
    paths:
      - "logos/token-logos/network/**/**"
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies and test
        run: pnpm install && pnpm test
        working-directory: './logos/token-logos'